import mongoose from 'mongoose';
import { Warehouse } from '../models/index.js';

mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost/warehouse-inventory', {
  useNewUrlParser: true,
  useUnifiedTopology: true
});

const productSeed = [{"productName":"Yukon","sqft":24,"quantity":1,"color":"Mauv"},
    {"productName":"Fit","sqft":14,"quantity":11,"color":"Red"},
    {"productName":"911","sqft":18,"quantity":26,"color":"Blue"},
    {"productName":"Corvette","sqft":24,"quantity":7,"color":"Goldenrod"},
    {"productName":"3500","sqft":20,"quantity":16,"color":"Khaki"},
    {"productName":"del Sol","sqft":24,"quantity":3,"color":"Maroon"},
    {"productName":"i-280","sqft":15,"quantity":6,"color":"Pink"},
    {"productName":"760","sqft":14,"quantity":23,"color":"Red"},
    {"productName":"Montero","sqft":20,"quantity":1,"color":"Goldenrod"},
    {"productName":"Murciélago","sqft":21,"quantity":24,"color":"Crimson"},
    {"productName":"Transit Connect","sqft":16,"quantity":2,"color":"Crimson"},
    {"productName":"LSS","sqft":14,"quantity":6,"color":"Yellow"},
    {"productName":"Econoline E250","sqft":16,"quantity":7,"color":"Turquoise"},
    {"productName":"Explorer","sqft":18,"quantity":10,"color":"Turquoise"},
    {"productName":"rio","sqft":19,"quantity":26,"color":"Pink"},
    {"productName":"R-Class","sqft":23,"quantity":29,"color":"Orange"},
    {"productName":"C70","sqft":20,"quantity":3,"color":"Mauv"},
    {"productName":"Equus","sqft":21,"quantity":25,"color":"Aquamarine"},
    {"productName":"Trans Sport","sqft":15,"quantity":12,"color":"Violet"},
    {"productName":"Tundra","sqft":15,"quantity":9,"color":"Maroon"},
    {"productName":"GS","sqft":21,"quantity":16,"color":"Puce"},
    {"productName":"H2","sqft":15,"quantity":14,"color":"Puce"},
    {"productName":"A4","sqft":19,"quantity":18,"color":"Aquamarine"},
    {"productName":"LaCrosse","sqft":21,"quantity":12,"color":"Teal"},
    {"productName":"Firefly","sqft":23,"quantity":17,"color":"Indigo"},
    {"productName":"Boxster","sqft":19,"quantity":21,"color":"Indigo"},
    {"productName":"Explorer","sqft":20,"quantity":15,"color":"Aquamarine"},
    {"productName":"ES","sqft":17,"quantity":19,"color":"Turquoise"},
    {"productName":"Blazer","sqft":20,"quantity":22,"color":"Maroon"},
    {"productName":"Riviera","sqft":21,"quantity":17,"color":"Aquamarine"},
    {"productName":"Continental GT","sqft":14,"quantity":1,"color":"Orange"},
    {"productName":"Solara","sqft":24,"quantity":17,"color":"Goldenrod"},
    {"productName":"Mirage","sqft":14,"quantity":17,"color":"Aquamarine"},
    {"productName":"Express 3500","sqft":17,"quantity":8,"color":"Pink"},
    {"productName":"Ram 1500","sqft":23,"quantity":20,"color":"Fuscia"},
    {"productName":"F250","sqft":21,"quantity":9,"color":"Violet"},
    {"productName":"Sonoma Club Coupe","sqft":15,"quantity":25,"color":"Maroon"},
    {"productName":"Monte Carlo","sqft":18,"quantity":30,"color":"Puce"},
    {"productName":"Versa","sqft":15,"quantity":17,"color":"Turquoise"},
    {"productName":"Concorde","sqft":17,"quantity":8,"color":"Crimson"},
    {"productName":"Sebring","sqft":17,"quantity":25,"color":"Puce"},
    {"productName":"Intrigue","sqft":19,"quantity":22,"color":"Indigo"},
    {"productName":"Spectra5","sqft":22,"quantity":18,"color":"Violet"},
    {"productName":"530","sqft":20,"quantity":10,"color":"Mauv"},
    {"productName":"Express 1500","sqft":22,"quantity":28,"color":"Khaki"},
    {"productName":"Sequoia","sqft":15,"quantity":15,"color":"Indigo"},
    {"productName":"Express 3500","sqft":23,"quantity":22,"color":"Orange"},
    {"productName":"RX","sqft":12,"quantity":13,"color":"Goldenrod"},
    {"productName":"Roadster","sqft":14,"quantity":5,"color":"Purple"},
    {"productName":"Commander","sqft":23,"quantity":24,"color":"Turquoise"},
    {"productName":"Exige","sqft":12,"quantity":23,"color":"Orange"},
    {"productName":"Mazda6","sqft":15,"quantity":27,"color":"Purple"},
    {"productName":"Altima","sqft":16,"quantity":10,"color":"Pink"},
    {"productName":"Villager","sqft":14,"quantity":12,"color":"Mauv"},
    {"productName":"Cayman","sqft":16,"quantity":9,"color":"Yellow"},
    {"productName":"4000s","sqft":17,"quantity":15,"color":"Aquamarine"},
    {"productName":"Insight","sqft":13,"quantity":24,"color":"Blue"},
    {"productName":"Pilot","sqft":21,"quantity":20,"color":"Goldenrod"},
    {"productName":"Highlander","sqft":19,"quantity":12,"color":"Yellow"},
    {"productName":"Yukon","sqft":13,"quantity":13,"color":"Blue"},
    {"productName":"Fifth Ave","sqft":19,"quantity":15,"color":"Violet"},
    {"productName":"Grand Caravan","sqft":12,"quantity":18,"color":"Crimson"},
    {"productName":"Land Cruiser","sqft":12,"quantity":19,"color":"Teal"},
    {"productName":"Sequoia","sqft":15,"quantity":4,"color":"Indigo"},
    {"productName":"Paseo","sqft":23,"quantity":13,"color":"Purple"},
    {"productName":"Milan","sqft":19,"quantity":22,"color":"Violet"},
    {"productName":"300","sqft":22,"quantity":30,"color":"Goldenrod"},
    {"productName":"Sequoia","sqft":22,"quantity":7,"color":"Crimson"},
    {"productName":"Passat","sqft":21,"quantity":23,"color":"Indigo"},
    {"productName":"S10","sqft":17,"quantity":18,"color":"Aquamarine"},
    {"productName":"Laser","sqft":12,"quantity":9,"color":"Yellow"},
    {"productName":"FJ Cruiser","sqft":24,"quantity":11,"color":"Yellow"},
    {"productName":"Corvette","sqft":20,"quantity":4,"color":"Purple"},
    {"productName":"Envoy","sqft":18,"quantity":19,"color":"Aquamarine"},
    {"productName":"Laser","sqft":12,"quantity":19,"color":"Turquoise"},
    {"productName":"Tracer","sqft":16,"quantity":19,"color":"Fuscia"},
    {"productName":"Challenger","sqft":21,"quantity":17,"color":"Turquoise"},
    {"productName":"A6","sqft":20,"quantity":23,"color":"Turquoise"},
    {"productName":"612 Scaglietti","sqft":22,"quantity":2,"color":"Yellow"},
    {"productName":"Ciera","sqft":15,"quantity":5,"color":"Violet"},
    {"productName":"Mazda6","sqft":19,"quantity":19,"color":"Maroon"},
    {"productName":"Corvette","sqft":22,"quantity":23,"color":"Violet"},
    {"productName":"Freestar","sqft":19,"quantity":16,"color":"Fuscia"},
    {"productName":"Yukon","sqft":17,"quantity":17,"color":"Crimson"},
    {"productName":"Eurovan","sqft":12,"quantity":7,"color":"Goldenrod"},
    {"productName":"LS","sqft":19,"quantity":24,"color":"Crimson"},
    {"productName":"Vitara","sqft":17,"quantity":8,"color":"Khaki"},
    {"productName":"Expedition EL","sqft":21,"quantity":9,"color":"Red"},
    {"productName":"ES","sqft":16,"quantity":30,"color":"Violet"},
    {"productName":"3000GT","sqft":18,"quantity":16,"color":"Aquamarine"},
    {"productName":"C70","sqft":16,"quantity":29,"color":"Aquamarine"},
    {"productName":"Murano","sqft":23,"quantity":14,"color":"Green"},
    {"productName":"Odyssey","sqft":22,"quantity":30,"color":"Green"},
    {"productName":"Amanti","sqft":12,"quantity":21,"color":"Green"},
    {"productName":"Mustang","sqft":16,"quantity":29,"color":"Pink"},
    {"productName":"Spyder","sqft":20,"quantity":5,"color":"Teal"},
    {"productName":"Blazer","sqft":15,"quantity":8,"color":"Red"},
    {"productName":"Venture","sqft":19,"quantity":11,"color":"Violet"},
    {"productName":"8 Series","sqft":21,"quantity":26,"color":"Goldenrod"},
    {"productName":"Corvette","sqft":21,"quantity":15,"color":"Fuscia"},
    {"productName":"W201","sqft":18,"quantity":5,"color":"Goldenrod"},
    {"productName":"Pathfinder","sqft":21,"quantity":5,"color":"Goldenrod"},
    {"productName":"tC","sqft":15,"quantity":9,"color":"Red"},
    {"productName":"Trooper","sqft":20,"quantity":6,"color":"Red"},
    {"productName":"Fifth Ave","sqft":20,"quantity":11,"color":"Khaki"},
    {"productName":"SC","sqft":16,"quantity":2,"color":"Purple"},
    {"productName":"MX-5","sqft":20,"quantity":11,"color":"Red"},
    {"productName":"Veracruz","sqft":19,"quantity":4,"color":"Mauv"},
    {"productName":"Firebird","sqft":17,"quantity":7,"color":"Green"},
    {"productName":"Venture","sqft":21,"quantity":3,"color":"Green"},
    {"productName":"Taurus","sqft":17,"quantity":24,"color":"Orange"},
    {"productName":"Sprinter","sqft":23,"quantity":20,"color":"Puce"},
    {"productName":"Avalon","sqft":19,"quantity":17,"color":"Pink"},
    {"productName":"Mazda5","sqft":23,"quantity":18,"color":"Turquoise"},
    {"productName":"Express 1500","sqft":18,"quantity":6,"color":"Indigo"},
    {"productName":"Grand Caravan","sqft":16,"quantity":12,"color":"Green"},
    {"productName":"RX-7","sqft":21,"quantity":2,"color":"Khaki"},
    {"productName":"Discovery","sqft":14,"quantity":15,"color":"Puce"},
    {"productName":"Viper","sqft":17,"quantity":25,"color":"Goldenrod"},
    {"productName":"Suburban 1500","sqft":20,"quantity":28,"color":"Indigo"},
    {"productName":"Sentra","sqft":16,"quantity":1,"color":"Indigo"},
    {"productName":"Swift","sqft":19,"quantity":12,"color":"Goldenrod"},
    {"productName":"Skylark","sqft":14,"quantity":4,"color":"Turquoise"},
    {"productName":"Sportage","sqft":20,"quantity":5,"color":"Orange"},
    {"productName":"IS F","sqft":13,"quantity":14,"color":"Turquoise"},
    {"productName":"Fox","sqft":17,"quantity":1,"color":"Violet"},
    {"productName":"3 Series","sqft":20,"quantity":11,"color":"Pink"},
    {"productName":"2500","sqft":13,"quantity":12,"color":"Yellow"},
    {"productName":"Expo","sqft":13,"quantity":27,"color":"Puce"},
    {"productName":"LS Hybrid","sqft":20,"quantity":26,"color":"Pink"},
    {"productName":"Escort","sqft":23,"quantity":9,"color":"Maroon"},
    {"productName":"Swift","sqft":14,"quantity":1,"color":"Blue"},
    {"productName":"Sierra 3500","sqft":21,"quantity":5,"color":"Purple"},
    {"productName":"Verano","sqft":13,"quantity":12,"color":"Pink"},
    {"productName":"Fox","sqft":24,"quantity":16,"color":"Puce"},
    {"productName":"Tredia","sqft":12,"quantity":22,"color":"Violet"},
    {"productName":"Defender 110","sqft":16,"quantity":13,"color":"Khaki"},
    {"productName":"GTO","sqft":14,"quantity":22,"color":"Orange"},
    {"productName":"MR2","sqft":24,"quantity":19,"color":"Fuscia"},
    {"productName":"V8 Vantage","sqft":24,"quantity":19,"color":"Red"},
    {"productName":"Sonoma Club Coupe","sqft":15,"quantity":19,"color":"Crimson"},
    {"productName":"Firefly","sqft":12,"quantity":4,"color":"Khaki"},
    {"productName":"SVX","sqft":14,"quantity":10,"color":"Red"},
    {"productName":"Carens","sqft":18,"quantity":10,"color":"Goldenrod"},
    {"productName":"Golf","sqft":22,"quantity":17,"color":"Maroon"},
    {"productName":"Voyager","sqft":17,"quantity":28,"color":"Violet"},
    {"productName":"H1","sqft":16,"quantity":5,"color":"Teal"},
    {"productName":"Camry Hybrid","sqft":14,"quantity":9,"color":"Orange"},
    {"productName":"Range Rover","sqft":23,"quantity":3,"color":"Red"},
    {"productName":"6 Series","sqft":12,"quantity":7,"color":"Khaki"},
    {"productName":"Caravan","sqft":23,"quantity":21,"color":"Green"},
    {"productName":"GL-Class","sqft":19,"quantity":21,"color":"Violet"},
    {"productName":"Journey","sqft":14,"quantity":4,"color":"Blue"},
    {"productName":"Thunderbird","sqft":20,"quantity":30,"color":"Teal"},
    {"productName":"Yukon","sqft":24,"quantity":7,"color":"Khaki"},
    {"productName":"Nitro","sqft":22,"quantity":3,"color":"Fuscia"},
    {"productName":"X5","sqft":14,"quantity":10,"color":"Yellow"},
    {"productName":"Town Car","sqft":23,"quantity":3,"color":"Indigo"},
    {"productName":"Cougar","sqft":23,"quantity":13,"color":"Orange"},
    {"productName":"Z4","sqft":18,"quantity":1,"color":"Fuscia"},
    {"productName":"CL-Class","sqft":13,"quantity":2,"color":"Turquoise"},
    {"productName":"Vandura 3500","sqft":12,"quantity":27,"color":"Turquoise"},
    {"productName":"Ram 1500","sqft":24,"quantity":30,"color":"Teal"},
    {"productName":"Savana 3500","sqft":12,"quantity":26,"color":"Pink"},
    {"productName":"Range Rover","sqft":17,"quantity":9,"color":"Orange"},
    {"productName":"Sienna","sqft":23,"quantity":4,"color":"Aquamarine"},
    {"productName":"Esprit","sqft":23,"quantity":5,"color":"Maroon"},
    {"productName":"Econoline E250","sqft":21,"quantity":3,"color":"Turquoise"},
    {"productName":"Montero","sqft":18,"quantity":11,"color":"Puce"},
    {"productName":"525","sqft":22,"quantity":23,"color":"Pink"},
    {"productName":"Xterra","sqft":12,"quantity":21,"color":"Violet"},
    {"productName":"Concorde","sqft":17,"quantity":13,"color":"Turquoise"},
    {"productName":"9-7X","sqft":14,"quantity":13,"color":"Pink"},
    {"productName":"QX56","sqft":23,"quantity":23,"color":"Indigo"},
    {"productName":"M-Class","sqft":15,"quantity":21,"color":"Blue"},
    {"productName":"MX-6","sqft":20,"quantity":25,"color":"Yellow"},
    {"productName":"Town Car","sqft":13,"quantity":16,"color":"Goldenrod"},
    {"productName":"CLK-Class","sqft":16,"quantity":25,"color":"Pink"},
    {"productName":"Thunderbird","sqft":24,"quantity":25,"color":"Orange"},
    {"productName":"Canyon","sqft":15,"quantity":10,"color":"Purple"},
    {"productName":"Spectra","sqft":18,"quantity":22,"color":"Fuscia"},
    {"productName":"Esprit","sqft":23,"quantity":1,"color":"Pink"},
    {"productName":"Dakota Club","sqft":24,"quantity":7,"color":"Goldenrod"},
    {"productName":"Protege","sqft":12,"quantity":17,"color":"Puce"},
    {"productName":"GT-R","sqft":22,"quantity":29,"color":"Purple"},
    {"productName":"911","sqft":14,"quantity":18,"color":"Fuscia"},
    {"productName":"LR3","sqft":16,"quantity":13,"color":"Fuscia"},
    {"productName":"Riviera","sqft":14,"quantity":12,"color":"Purple"},
    {"productName":"Galaxie","sqft":12,"quantity":5,"color":"Puce"},
    {"productName":"Allroad","sqft":21,"quantity":8,"color":"Maroon"},
    {"productName":"S-Class","sqft":12,"quantity":27,"color":"Puce"},
    {"productName":"Passat","sqft":22,"quantity":18,"color":"Turquoise"},
    {"productName":"Passat","sqft":12,"quantity":22,"color":"Fuscia"},
    {"productName":"Nitro","sqft":24,"quantity":29,"color":"Fuscia"},
    {"productName":"Z8","sqft":14,"quantity":14,"color":"Mauv"},
    {"productName":"RDX","sqft":23,"quantity":27,"color":"Yellow"},
    {"productName":"XJ Series","sqft":13,"quantity":16,"color":"Puce"},
    {"productName":"Bronco II","sqft":14,"quantity":27,"color":"Red"},
    {"productName":"Skylark","sqft":20,"quantity":9,"color":"Fuscia"},
    {"productName":"929","sqft":23,"quantity":3,"color":"Teal"}
];

const productSeedV2 = [{"productName":"Avalon","sqft":20,"quantity":11,"color":"Puce"},
{"productName":"Bonneville","sqft":22,"quantity":2,"color":"Yellow"},
{"productName":"Suburban 2500","sqft":23,"quantity":13,"color":"Teal"},
{"productName":"Corvette","sqft":19,"quantity":28,"color":"Indigo"},
{"productName":"Miata MX-5","sqft":12,"quantity":14,"color":"Indigo"},
{"productName":"QX","sqft":12,"quantity":22,"color":"Indigo"},
{"productName":"VehiCROSS","sqft":24,"quantity":22,"color":"Aquamarine"},
{"productName":"Tacoma","sqft":19,"quantity":30,"color":"Green"},
{"productName":"Tundra","sqft":20,"quantity":28,"color":"Puce"},
{"productName":"Town Car","sqft":18,"quantity":27,"color":"Indigo"},
{"productName":"SLK-Class","sqft":14,"quantity":13,"color":"Maroon"},
{"productName":"RAV4","sqft":12,"quantity":10,"color":"Red"},
{"productName":"Verona","sqft":18,"quantity":20,"color":"Green"},
{"productName":"Countach","sqft":18,"quantity":24,"color":"Red"},
{"productName":"A8","sqft":16,"quantity":21,"color":"Blue"},
{"productName":"Tiburon","sqft":18,"quantity":12,"color":"Khaki"},
{"productName":"B-Series","sqft":17,"quantity":8,"color":"Yellow"},
{"productName":"Ghost","sqft":24,"quantity":4,"color":"Goldenrod"},
{"productName":"500","sqft":14,"quantity":8,"color":"Mauv"},
{"productName":"IS F","sqft":20,"quantity":21,"color":"Teal"},
{"productName":"X5","sqft":17,"quantity":10,"color":"Maroon"},
{"productName":"Sequoia","sqft":22,"quantity":19,"color":"Puce"},
{"productName":"626","sqft":20,"quantity":24,"color":"Maroon"},
{"productName":"EXP","sqft":15,"quantity":18,"color":"Turquoise"},
{"productName":"Savana 3500","sqft":17,"quantity":19,"color":"Green"},
{"productName":"Savana 2500","sqft":17,"quantity":1,"color":"Mauv"},
{"productName":"Rendezvous","sqft":14,"quantity":17,"color":"Turquoise"},
{"productName":"Grand Am","sqft":23,"quantity":21,"color":"Crimson"},
{"productName":"S4","sqft":18,"quantity":30,"color":"Fuscia"},
{"productName":"TL","sqft":21,"quantity":23,"color":"Maroon"},
{"productName":"Range Rover","sqft":21,"quantity":25,"color":"Yellow"},
{"productName":"RSX","sqft":20,"quantity":12,"color":"Turquoise"},
{"productName":"F-Series","sqft":22,"quantity":25,"color":"Teal"},
{"productName":"80","sqft":18,"quantity":6,"color":"Aquamarine"},
{"productName":"Laser","sqft":13,"quantity":14,"color":"Blue"},
{"productName":"Z3","sqft":15,"quantity":11,"color":"Yellow"},
{"productName":"4Runner","sqft":14,"quantity":18,"color":"Violet"},
{"productName":"S10 Blazer","sqft":17,"quantity":24,"color":"Crimson"},
{"productName":"Range Rover","sqft":20,"quantity":28,"color":"Khaki"},
{"productName":"Fiero","sqft":12,"quantity":12,"color":"Indigo"},
{"productName":"TL","sqft":17,"quantity":12,"color":"Purple"},
{"productName":"Celica","sqft":23,"quantity":15,"color":"Goldenrod"},
{"productName":"Outback","sqft":15,"quantity":1,"color":"Crimson"},
{"productName":"LTD","sqft":14,"quantity":2,"color":"Violet"},
{"productName":"Leone","sqft":12,"quantity":14,"color":"Puce"},
{"productName":"Thunderbird","sqft":13,"quantity":6,"color":"Yellow"},
{"productName":"Corvette","sqft":20,"quantity":16,"color":"Mauv"},
{"productName":"CX-7","sqft":20,"quantity":17,"color":"Crimson"},
{"productName":"Alcyone SVX","sqft":12,"quantity":7,"color":"Turquoise"},
{"productName":"Caravan","sqft":24,"quantity":17,"color":"Teal"},
{"productName":"RL","sqft":14,"quantity":12,"color":"Indigo"},
{"productName":"MX-5","sqft":20,"quantity":19,"color":"Aquamarine"},
{"productName":"XJ","sqft":17,"quantity":25,"color":"Teal"},
{"productName":"Elantra","sqft":13,"quantity":17,"color":"Indigo"},
{"productName":"F250","sqft":17,"quantity":16,"color":"Crimson"},
{"productName":"Corvette","sqft":15,"quantity":11,"color":"Puce"},
{"productName":"Mustang","sqft":20,"quantity":23,"color":"Fuscia"},
{"productName":"Rodeo","sqft":24,"quantity":4,"color":"Maroon"},
{"productName":"Town Car","sqft":22,"quantity":24,"color":"Maroon"},
{"productName":"Continental","sqft":21,"quantity":22,"color":"Khaki"},
{"productName":"ZDX","sqft":22,"quantity":27,"color":"Indigo"},
{"productName":"Bronco II","sqft":21,"quantity":13,"color":"Goldenrod"},
{"productName":"Ram 2500 Club","sqft":20,"quantity":12,"color":"Orange"},
{"productName":"Odyssey","sqft":23,"quantity":28,"color":"Goldenrod"},
{"productName":"Continental Flying Spur","sqft":20,"quantity":30,"color":"Khaki"},
{"productName":"Regal","sqft":16,"quantity":25,"color":"Red"},
{"productName":"Outback","sqft":20,"quantity":29,"color":"Goldenrod"},
{"productName":"Familia","sqft":20,"quantity":1,"color":"Indigo"},
{"productName":"Trooper","sqft":15,"quantity":17,"color":"Teal"},
{"productName":"Impreza","sqft":21,"quantity":12,"color":"Crimson"},
{"productName":"Envoy","sqft":14,"quantity":11,"color":"Mauv"},
{"productName":"IS-F","sqft":13,"quantity":1,"color":"Puce"},
{"productName":"XC90","sqft":16,"quantity":28,"color":"Teal"},
{"productName":"Endeavor","sqft":19,"quantity":2,"color":"Indigo"},
{"productName":"Park Avenue","sqft":22,"quantity":2,"color":"Red"},
{"productName":"Golf III","sqft":16,"quantity":11,"color":"Yellow"},
{"productName":"Diamante","sqft":22,"quantity":3,"color":"Crimson"},
{"productName":"Prizm","sqft":22,"quantity":22,"color":"Blue"},
{"productName":"Safari","sqft":12,"quantity":28,"color":"Yellow"},
{"productName":"MKX","sqft":19,"quantity":20,"color":"Turquoise"},
{"productName":"Tracer","sqft":19,"quantity":22,"color":"Red"},
{"productName":"Stanza","sqft":24,"quantity":24,"color":"Aquamarine"},
{"productName":"Town Car","sqft":17,"quantity":8,"color":"Pink"},
{"productName":"Stratus","sqft":17,"quantity":27,"color":"Purple"},
{"productName":"Express 2500","sqft":17,"quantity":7,"color":"Green"},
{"productName":"Sable","sqft":18,"quantity":23,"color":"Pink"},
{"productName":"Bonneville","sqft":20,"quantity":26,"color":"Blue"},
{"productName":"Spyder","sqft":13,"quantity":11,"color":"Purple"},
{"productName":"Explorer Sport Trac","sqft":18,"quantity":1,"color":"Puce"},
{"productName":"F250","sqft":19,"quantity":22,"color":"Fuscia"},
{"productName":"Boxster","sqft":13,"quantity":16,"color":"Pink"},
{"productName":"RL","sqft":21,"quantity":17,"color":"Teal"},
{"productName":"90","sqft":24,"quantity":10,"color":"Teal"},
{"productName":"911","sqft":15,"quantity":15,"color":"Violet"},
{"productName":"C70","sqft":14,"quantity":25,"color":"Violet"},
{"productName":"Q","sqft":18,"quantity":2,"color":"Aquamarine"},
{"productName":"Suburban 2500","sqft":15,"quantity":18,"color":"Pink"},
{"productName":"Contour","sqft":21,"quantity":15,"color":"Red"},
{"productName":"Previa","sqft":19,"quantity":3,"color":"Violet"},
{"productName":"300M","sqft":19,"quantity":15,"color":"Fuscia"},
{"productName":"Breeze","sqft":24,"quantity":22,"color":"Puce"},
{"productName":"Suburban 1500","sqft":15,"quantity":25,"color":"Yellow"},
{"productName":"Century","sqft":23,"quantity":8,"color":"Maroon"},
{"productName":"H1","sqft":23,"quantity":15,"color":"Khaki"},
{"productName":"Xterra","sqft":17,"quantity":1,"color":"Mauv"},
{"productName":"B-Series","sqft":13,"quantity":7,"color":"Red"},
{"productName":"Stratus","sqft":21,"quantity":3,"color":"Goldenrod"},
{"productName":"Aurora","sqft":14,"quantity":7,"color":"Blue"},
{"productName":"Outlander","sqft":18,"quantity":3,"color":"Goldenrod"},
{"productName":"4Runner","sqft":17,"quantity":2,"color":"Puce"},
{"productName":"Sportvan G30","sqft":21,"quantity":6,"color":"Yellow"},
{"productName":"Avalon","sqft":20,"quantity":25,"color":"Green"},
{"productName":"Summit","sqft":13,"quantity":15,"color":"Goldenrod"},
{"productName":"SL-Class","sqft":16,"quantity":4,"color":"Fuscia"},
{"productName":"Avalon","sqft":14,"quantity":22,"color":"Puce"},
{"productName":"Skylark","sqft":22,"quantity":23,"color":"Puce"},
{"productName":"Murano","sqft":21,"quantity":29,"color":"Orange"},
{"productName":"Ram 3500","sqft":20,"quantity":5,"color":"Violet"},
{"productName":"Accord","sqft":12,"quantity":14,"color":"Maroon"},
{"productName":"9000","sqft":19,"quantity":25,"color":"Khaki"},
{"productName":"GT500","sqft":23,"quantity":26,"color":"Red"},
{"productName":"Savana 1500","sqft":17,"quantity":25,"color":"Violet"},
{"productName":"Silverado 2500","sqft":15,"quantity":1,"color":"Orange"},
{"productName":"1500","sqft":21,"quantity":14,"color":"Indigo"},
{"productName":"Ipsum","sqft":19,"quantity":27,"color":"Teal"},
{"productName":"T100 Xtra","sqft":15,"quantity":23,"color":"Mauv"},
{"productName":"DTS","sqft":17,"quantity":13,"color":"Khaki"},
{"productName":"Sentra","sqft":14,"quantity":27,"color":"Pink"},
{"productName":"C70","sqft":16,"quantity":12,"color":"Red"},
{"productName":"Murano","sqft":23,"quantity":7,"color":"Pink"},
{"productName":"Eclipse","sqft":13,"quantity":9,"color":"Blue"},
{"productName":"XK Series","sqft":19,"quantity":2,"color":"Red"},
{"productName":"Ranger","sqft":24,"quantity":25,"color":"Puce"},
{"productName":"928","sqft":21,"quantity":3,"color":"Goldenrod"},
{"productName":"Corvette","sqft":24,"quantity":27,"color":"Goldenrod"},
{"productName":"Taurus","sqft":12,"quantity":1,"color":"Orange"},
{"productName":"3 Series","sqft":22,"quantity":4,"color":"Purple"},
{"productName":"Coupe Quattro","sqft":22,"quantity":2,"color":"Red"},
{"productName":"Coachbuilder","sqft":18,"quantity":14,"color":"Yellow"},
{"productName":"Tredia","sqft":16,"quantity":7,"color":"Blue"},
{"productName":"Silverado 1500","sqft":24,"quantity":25,"color":"Maroon"},
{"productName":"Tempo","sqft":14,"quantity":10,"color":"Purple"},
{"productName":"Mariner","sqft":17,"quantity":28,"color":"Pink"},
{"productName":"New Yorker","sqft":12,"quantity":20,"color":"Indigo"},
{"productName":"Camry","sqft":12,"quantity":29,"color":"Indigo"},
{"productName":"Catera","sqft":14,"quantity":7,"color":"Turquoise"},
{"productName":"Golf III","sqft":12,"quantity":6,"color":"Goldenrod"},
{"productName":"Eldorado","sqft":22,"quantity":19,"color":"Indigo"},
{"productName":"Q5","sqft":13,"quantity":5,"color":"Orange"},
{"productName":"Uplander","sqft":17,"quantity":20,"color":"Crimson"},
{"productName":"Montero","sqft":22,"quantity":16,"color":"Fuscia"},
{"productName":"Chevette","sqft":17,"quantity":5,"color":"Maroon"},
{"productName":"NSX","sqft":18,"quantity":30,"color":"Violet"},
{"productName":"Azera","sqft":13,"quantity":14,"color":"Puce"},
{"productName":"Cabriolet","sqft":17,"quantity":26,"color":"Green"},
{"productName":"Concorde","sqft":23,"quantity":16,"color":"Violet"},
{"productName":"Explorer","sqft":14,"quantity":26,"color":"Violet"},
{"productName":"Windstar","sqft":20,"quantity":22,"color":"Orange"},
{"productName":"W201","sqft":17,"quantity":9,"color":"Aquamarine"},
{"productName":"M5","sqft":13,"quantity":24,"color":"Orange"},
{"productName":"Land Cruiser","sqft":19,"quantity":19,"color":"Aquamarine"},
{"productName":"Taurus","sqft":22,"quantity":20,"color":"Teal"},
{"productName":"Grand Cherokee","sqft":16,"quantity":29,"color":"Mauv"},
{"productName":"Sebring","sqft":15,"quantity":2,"color":"Blue"},
{"productName":"Sonata","sqft":24,"quantity":11,"color":"Fuscia"},
{"productName":"Silverado","sqft":19,"quantity":27,"color":"Green"},
{"productName":"B2500","sqft":21,"quantity":2,"color":"Yellow"},
{"productName":"Solara","sqft":12,"quantity":20,"color":"Khaki"},
{"productName":"Sentra","sqft":12,"quantity":12,"color":"Teal"},
{"productName":"Ram 1500 Club","sqft":14,"quantity":21,"color":"Fuscia"},
{"productName":"Park Avenue","sqft":16,"quantity":17,"color":"Fuscia"},
{"productName":"6000","sqft":14,"quantity":15,"color":"Orange"},
{"productName":"LHS","sqft":17,"quantity":26,"color":"Fuscia"},
{"productName":"Lancer","sqft":20,"quantity":17,"color":"Khaki"},
{"productName":"SJ","sqft":23,"quantity":18,"color":"Violet"},
{"productName":"Trooper","sqft":21,"quantity":2,"color":"Fuscia"},
{"productName":"T100","sqft":14,"quantity":23,"color":"Aquamarine"},
{"productName":"Traverse","sqft":17,"quantity":19,"color":"Khaki"},
{"productName":"Cirrus","sqft":14,"quantity":25,"color":"Pink"},
{"productName":"Countach","sqft":19,"quantity":7,"color":"Maroon"},
{"productName":"S-Class","sqft":13,"quantity":16,"color":"Aquamarine"},
{"productName":"900","sqft":20,"quantity":12,"color":"Khaki"},
{"productName":"Vantage","sqft":12,"quantity":27,"color":"Blue"},
{"productName":"Bonneville","sqft":19,"quantity":20,"color":"Crimson"},
{"productName":"Civic","sqft":17,"quantity":1,"color":"Crimson"},
{"productName":"Crown Victoria","sqft":17,"quantity":8,"color":"Red"},
{"productName":"Ram 1500","sqft":20,"quantity":22,"color":"Indigo"},
{"productName":"Phantom","sqft":20,"quantity":26,"color":"Fuscia"},
{"productName":"Quest","sqft":18,"quantity":14,"color":"Indigo"},
{"productName":"Mirage","sqft":21,"quantity":26,"color":"Red"},
{"productName":"Rally Wagon G3500","sqft":13,"quantity":9,"color":"Teal"},
{"productName":"Grand Caravan","sqft":14,"quantity":3,"color":"Red"},
{"productName":"Sable","sqft":14,"quantity":3,"color":"Red"},
{"productName":"Tracker","sqft":16,"quantity":10,"color":"Pink"},
{"productName":"Boxster","sqft":16,"quantity":27,"color":"Red"},
{"productName":"Camaro","sqft":23,"quantity":18,"color":"Turquoise"},
{"productName":"RAV4","sqft":22,"quantity":4,"color":"Red"},
{"productName":"MX-6","sqft":12,"quantity":27,"color":"Turquoise"},
{"productName":"Savana 3500","sqft":19,"quantity":2,"color":"Teal"},
{"productName":"Flex","sqft":24,"quantity":30,"color":"Aquamarine"},
{"productName":"Cordia","sqft":22,"quantity":5,"color":"Teal"},
{"productName":"Navigator","sqft":16,"quantity":14,"color":"Aquamarine"},
{"productName":"Escalade","sqft":12,"quantity":21,"color":"Green"},
{"productName":"Mountaineer","sqft":14,"quantity":27,"color":"Crimson"},
{"productName":"5 Series","sqft":21,"quantity":2,"color":"Orange"},
{"productName":"Pajero","sqft":15,"quantity":26,"color":"Blue"},
{"productName":"Windstar","sqft":13,"quantity":30,"color":"Blue"},
{"productName":"Regal","sqft":16,"quantity":25,"color":"Indigo"},
{"productName":"Mirage","sqft":20,"quantity":3,"color":"Yellow"},
{"productName":"LS","sqft":18,"quantity":4,"color":"Green"},
{"productName":"Crown Victoria","sqft":21,"quantity":28,"color":"Maroon"},
{"productName":"3 Series","sqft":16,"quantity":10,"color":"Yellow"},
{"productName":"Q7","sqft":21,"quantity":19,"color":"Fuscia"},
{"productName":"MPV","sqft":17,"quantity":22,"color":"Teal"},
{"productName":"4000s Quattro","sqft":14,"quantity":30,"color":"Blue"},
{"productName":"S10","sqft":16,"quantity":22,"color":"Blue"},
{"productName":"3500 Club Coupe","sqft":24,"quantity":2,"color":"Pink"},
{"productName":"LTD","sqft":22,"quantity":10,"color":"Goldenrod"},
{"productName":"A8","sqft":12,"quantity":2,"color":"Red"},
{"productName":"SJ","sqft":14,"quantity":19,"color":"Violet"},
{"productName":"960","sqft":18,"quantity":5,"color":"Goldenrod"},
{"productName":"Club Wagon","sqft":23,"quantity":27,"color":"Turquoise"},
{"productName":"F250","sqft":22,"quantity":1,"color":"Yellow"},
{"productName":"Cougar","sqft":21,"quantity":25,"color":"Red"},
{"productName":"C8","sqft":12,"quantity":22,"color":"Violet"},
{"productName":"5 Series","sqft":23,"quantity":24,"color":"Turquoise"},
{"productName":"E250","sqft":24,"quantity":26,"color":"Crimson"},
{"productName":"rio","sqft":24,"quantity":1,"color":"Goldenrod"},
{"productName":"Impreza","sqft":19,"quantity":17,"color":"Fuscia"},
{"productName":"300SD","sqft":22,"quantity":16,"color":"Purple"},
{"productName":"7 Series","sqft":19,"quantity":29,"color":"Red"},
{"productName":"Azure","sqft":23,"quantity":1,"color":"Purple"},
{"productName":"Ridgeline","sqft":18,"quantity":16,"color":"Red"},
{"productName":"EX","sqft":22,"quantity":15,"color":"Goldenrod"},
{"productName":"E150","sqft":24,"quantity":22,"color":"Purple"},
{"productName":"CLK-Class","sqft":19,"quantity":29,"color":"Maroon"},
{"productName":"Forenza","sqft":15,"quantity":13,"color":"Yellow"},
{"productName":"Firefly","sqft":21,"quantity":22,"color":"Purple"},
{"productName":"GX","sqft":21,"quantity":4,"color":"Green"},
{"productName":"911","sqft":13,"quantity":5,"color":"Goldenrod"},
{"productName":"Supra","sqft":20,"quantity":11,"color":"Fuscia"},
{"productName":"Murciélago","sqft":21,"quantity":28,"color":"Goldenrod"},
{"productName":"7 Series","sqft":21,"quantity":12,"color":"Yellow"},
{"productName":"CL","sqft":20,"quantity":10,"color":"Goldenrod"},
{"productName":"Sienna","sqft":19,"quantity":10,"color":"Blue"},
{"productName":"Legacy","sqft":17,"quantity":23,"color":"Pink"},
{"productName":"Bronco II","sqft":21,"quantity":6,"color":"Yellow"},
{"productName":"Sidekick","sqft":23,"quantity":14,"color":"Yellow"},
{"productName":"XL-7","sqft":15,"quantity":25,"color":"Turquoise"},
{"productName":"FX","sqft":21,"quantity":13,"color":"Yellow"}]

async function runSeed() {
    try{
        let count = 0;
        // let getAllcompanies = await Company.find({});
        let getAllwarehouses = await Warehouse.find({});
        // console.log(getAllwarehouses);
        for( const product of productSeedV2 ){
            let randomIndex = Math.floor(Math.random() * getAllwarehouses.length);
            // console.log(randomIndex);
            let addedCurrentCapacity = getAllwarehouses[randomIndex].currentCapacity + product.sqft * product.quantity;
            await Warehouse.findByIdAndUpdate(getAllwarehouses[randomIndex]._id, {$set: {currentCapacity: addedCurrentCapacity}, $push: {product : product} })
    
            count++;
        }
        console.log(count+ " records inserted!");
        mongoose.connection.close();
        process.exit(0);
    }catch(err) {
        console.error(err);
        mongoose.connection.close();
        process.exit(1);
    }
}

runSeed();